### ISSUE TITLE
Make VoilaApp inherit from JupyterApp?

### ISSUE THREAD

**Issue by maartenbreddels** [QuantStack/voila#245]
We now inherit from Application, should we inherit from JupyterApp (see discussion in #216) , or can jupyter_server help out here?

**Comment by SylvainCorlay** [comment]
I think that we should wait for the ExtensionApp system to be in jupyter_server and have voila be an ExtensionApp.

**Comment by vidartf** [comment]
Anything I can do to move this along? :)

**Comment by vidartf** [comment]
Xref https://github.com/jupyter/jupyter_server/pull/48

**Comment by SylvainCorlay** [comment]
@vidartf I am fine with the current state of the PR. How about we merge it today. I just leave it open so that you have a chance to give it a look?

One thought that relates to voila:
 
 - once we adopt this approach, we will make `voila` an `ExtensionApp` all the time. This will allow us to drop the `VoilaConfiguration` mixin and have all the configuration into `VoilaApp`.
 - then `jupyter voila` will run a `jupyter_server` and with the start URL set to `/voila`.
 - we will then probably want the `voila` command line to be an alias on `jupyter voila`?
    (but with an additional option passed to `jupyter-voila` when using the `voila` alias that disables all other jupyter_server extensions such as notebook, so that we don't serve the notebook or jupyterlab by accident, and give a means to execute arbitrary code.

**Comment by vidartf** [comment]
@SylvainCorlay Regarding your third point: Which bit is it that will end up loading the different server extensions? The `ExtensionApp`, or the contained `ServerApp`? Would it be possible for the extension app to have a different configuration set of server extensions? E.g. each extension app could choose either:
- To inherit all extensions from parent (`jupyter serverextension enable`), plus any extensions specifically enabled for it, minus any extensions specifically disabled for it (enabled/disabled by user).
- To not inherit any extensions from parent, but only have extensions specifically enabled for it (useful for voila).

**Comment by Zsailer** [comment]
See #270

**Comment by maartenbreddels** [comment]
Won't do, #270 is better
