### ISSUE TITLE
Frontend stuck when rendering a notebook

### ISSUE THREAD

**Issue by adriendelsalle** [QuantStack/voila#375]
Hi everyone
Thanks for this great work! Please find hereafter what could be a *bug* to be confirmed.

Description/Bug behaviour
--
When `voilà` starts rendering a notebook using the notebook or JLab extensions, all the frontend is stuck as long as `voilà` job is not done:
- impossible to execute another notebook
- navigation panel does not respond (not able to change directory etc.)
- keyboard inputs are not reflected (in an open terminal or a notebook) but they are buffered and displayed when `voilà` job is finished

 I checked that the classic notebook reproduces this behaviour switching from `/lab` to `/tree`.

Env
--
I'm using `Jlab` from a `JHub` docker deployment.
Spawns are based on the jupyter docker-stack `base-notebook`, so O/S is Ubuntu 18.04.
I update some packages in a custom `docker` image as following:

package | version | build | repo
--- | --- | --- | ---
jupyter_client | 5.3.1 | py_0  | conda-forge
jupyter_core          |      4.4.0               |         py_0  |    conda-forge
jupyter_server        |      0.1.1       |               py37_0    |  conda-forge
jupyterhub        |          1.0.0       |               py37_0   |   conda-forge
jupyterlab           |       1.1.1            |            py_0   |   conda-forge
jupyterlab_pygments     |    0.1.0       |                 py_0  |    conda-forge
jupyterlab_server        |   1.0.0           |             py_1   |   conda-forge
notebook          |         6.0.0              |       py37_0   |  conda-forge
voila               |       0.1.10              |        py_0   |  conda-forge

Expected behaviour
--
Asynchronous render of the notebook(s) with `voilà`

Let me know if more information is necessary. Don't hesitate to correct/complete this report if I missed something!

**Comment by adriendelsalle** [comment]
Sorry I just saw @maartenbreddels #374

**Comment by jtpio** [comment]
Thanks @adriendelsalle for the detailed report.

Are you using voila as a server extension? It sounds very related to #363 (and #374 as you pointed out).

**Comment by maartenbreddels** [comment]
Thanks for the report, I think this stresses how important #374 is.

**Comment by jtpio** [comment]
In short:

- Server extension usually add functionality and endpoints to handle requests to the server (Jupyter Server or the Notebook Server for example). In the case of voila it is the handler that renders notebooks into dashboards.
- The noteboook extensions add frontend related components. They can depend on server extensions, which is the case for voila (calling the right endpoint when clicking on the button).
- Lab extensions also add frontend components and can optionally depend on server extensions (which is the case for the voila preview extension too).
- the `plotly` and `pythreejs` libraries also have bundles for the classic notebook that voila is able to find and reuse, which is why it is working with voila.

Yuvi wrote a nice article recently on the Jupyter blog on how extensions work in the Jupyter ecosystem. That could help clarify some points too: https://blog.jupyter.org/99-ways-to-extend-the-jupyter-ecosystem-11e5dab7c54

**Comment by jtpio** [comment]
@adriendelsalle is it ok if we close this issue in favor of #363?

And continue the discussion about the architecture in #378?

**Comment by adriendelsalle** [comment]
Yes sure @jtpio
Thanks!
