### ISSUE TITLE
Kernel shutdown on page refresh

### ISSUE THREAD

**Issue by jtpio** [QuantStack/voila#55]
Looks like kernels are not shut down when refreshing the page (using the standalone app):

![voila-kernels](https://user-images.githubusercontent.com/591645/51799790-1badfe00-2226-11e9-87eb-8b4ab62d7a0b.gif)

Seems to be related to how the `beforeunload` event is triggered:

https://github.com/QuantStack/voila/blob/c437a7fc564aee20e76526fa3c9acc5a5fef326f/voila/static/main.js#L12-L14

**Comment by jf---** [comment]
Ran into the same thing today; 

- especially when hitting reload for ~10 repeatedly, this indeed results in 10x new kernels spinning up.

The reason why the kernels arent shutting down due to:
https://github.com/QuantStack/voila/blob/c437a7fc564aee20e76526fa3c9acc5a5fef326f/voila/app.py#L154-L162

While its too easy to spin up / [forkbomb](https://en.wikipedia.org/wiki/Fork_bomb) the server, at least processes do get reap'd when the following options are thrown in the mix:

```python
        self.kernel_manager = MappingKernelManager(
            cull_busy=False,
            cull_connected=False,
            cull_idle_timeout=6,
            kernel_info_timeout=12,
           ...
```

**Comment by jtpio** [comment]
@jf--- Looked at it earlier today with the intent of switching from using voila as a server extension to the standalone app. As a server extension the kernel culling can be set via the notebook config.

> ```python
>         self.kernel_manager = MappingKernelManager(
>             cull_busy=False,
>             cull_connected=False,
>             cull_idle_timeout=6,
>             kernel_info_timeout=12,
>            ...
> ```
> 
> ( PR follows shortly )

I opened #80, but feel free to comment or add anything missing against this PR.

**Comment by jf---** [comment]
hi @jtpio , so the PR misses out on a few things I think:

First, the `cull_connected` should be True ( yikes, excuse me... ) and is missing in the PR.
This is critical, since otherwise effectively no culling will take place.

```python
           cull_busy=False,
            cull_connected=True,
```

Furthermore, I do think that healthy defaults need to be set for `cull_idle_time` and `kernel_info_timeout`

```python
            cull_idle_timeout=6,
            kernel_info_timeout=12,
```

As the PR is as of now, the issue effectively isn't resolved, since the defaults yields the same program state as pre-PR...

That said, IMO there's quite a difference of running `voila` on a local network, where you might be more conservative in cleaning zombie kernels ( I did run into a situation the process pool did get exhausted / where I could no longer run any shell commands on a test server ). 

Therefore since it is currently straightfwd to forkbomb a server, I think the defaults should ackowledge this.

**Comment by jtpio** [comment]
`cull_idle_timeout` and `cull_interval` should be enough to mitigate the issue when hitting reload several times in a row.
These parameters are already available when using voila as a server extension and the kernels get culled as expected when the page is refreshed or the tab is closed.

Regarding the defaults, it depends on how the dashboards are being used. In some cases enabling `cull_connected` by default can be considered unexpected.

Overall this will become easier to manage when the voila standalone app supports the traitlets configuration system (cf https://github.com/QuantStack/voila/pull/84).

**Comment by maartenbreddels** [comment]
Coming back to the original issue, I do see that kernel shutdown is being triggered on page refresh with chrome, or with navigation away from a page. It does not trigger it when closing a tab. I think we can tackle this once we have a better idea on session/kernel reuse etc.

**Comment by maartenbreddels** [comment]
Fixed in https://github.com/QuantStack/voila/pull/147

**Comment by jf---** [comment]
@maartenbreddels , would you mind commenting briefly on how the changes in #147 wedge into resolving this issue? I'm curious since on the surface the PR doesn't deal with aspects of session/kernel reuse

**Comment by eromoe** [comment]
How do I prevernt shutdown and restart ?
Because loading data is big, I would like reuse data in memory .

**Comment by maartenbreddels** [comment]
see https://github.com/voila-dashboards/voila/issues/527
